import React from 'react'
import nopfp from '../../../Assets/pfp.jpg'
import mariah from '../../../Assets/Mariah.jpg'
import anthone from '../../../Assets/Anthone.jpg'
import stephnie from '../../../Assets/Stephnie.jpg'
import kim from '../../../Assets/Kim.jpg'
import goldfelt from '../../../Assets/Goldfelt.jpg'
import whitman from '../../../Assets/Whitman.jpg'
import '../../../CSS/Main Content/Staff/Staff.css'
import StaffCards from '../Sections/Staff Sections/StaffCards'

const staffMembers = [
  {
    imgSrc: goldfelt,
    name: "Dr. Goldfelt",
    bio: "j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df"
  },
  {
    imgSrc: whitman,
    name: "Dr. Whitman",
    bio: "j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df"
  },
  {
    imgSrc: mariah,
    name: "Mariah",
    bio: "j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df"
  },
  {
    imgSrc: anthone,
    name: "Anthone",
    bio: "j ssdfkj sdfkj sdfkj sdfkjs dfkjs df j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df"
  },
  {
    imgSrc: stephnie,
    name: "Stephnie",
    bio: "j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df"
  },
  {
    imgSrc: kim,
    name: "Kim",
    bio: "j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df"
  },
]
export default function Staff() {
  return (
    <div>
      <StaffCards staffMembers={staffMembers} />
    </div>
  )
}
