import React from 'react'
import StaffCard from '../../Dynamic Templates/StaffCard'
import image from '../../../Assets/pfp.jpg'
import '../../../CSS/Main Content/Staff/Staff.css'
import StaffCards from '../Sections/Staff Sections/StaffCards'

const staffMembers = [
  {
    imgSrc: image,
    name: "Staff Person",
    bio: "j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df"
  },
  {
    imgSrc: image,
    name: "John Doe",
    bio: "j ssdfkj sdfkj sdfkj sdfkjs dfkjs df j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df"
  },
  {
    imgSrc: image,
    name: "John Doe",
    bio: "j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df"
  },
  {
    imgSrc: image,
    name: "John Doe",
    bio: "j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df"
  },
  {
    imgSrc: image,
    name: "John Doe",
    bio: "j sdfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df"
  },
  {
    imgSrc: image,
    name: "John Doe",
    bio: "j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkjfkj sdfkj sdfkj sdfkjs dfkjs df j sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs dfj sdfkj sdfkj dfkj dkfj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkj sdfkjs dfkjs df"
  },
]
export default function Staff() {
  return (
    <div>
      <StaffCards staffMembers={staffMembers} />
    </div>
  )
}
